# Generated by Django 5.2.3 on 2025-08-12 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matriculation Number')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('level', models.CharField(max_length=10, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.course')),
            ],
            options={
                'verbose_name': 'Assigned Course',
                'verbose_name_plural': 'Assigned Courses',
                'ordering': ['session', 'semester', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationOfficerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Officer Assignment',
                'verbose_name_plural': 'Registration Officer Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_data', models.CharField(choices=[('not_enrolled', 'Not Enrolled'), ('enrolled', 'Enrolled'), ('error', 'Error')], default='not_enrolled', max_length=20, verbose_name='Fingerprint Status')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.student')),
            ],
        ),
    ]
