# Generated by Django 5.2.5 on 2025-08-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'session', 'semester')},
        ),
    ]
