# Generated by Django 5.2.3 on 2025-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Level'),
        ),
    ]
