# Generated by Django 5.2.5 on 2025-08-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0002_fix_enrollment_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course', 'session', 'semester')},
        ),
    ]
