# Generated by Django 5.2.3 on 2025-08-13 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0002_alter_student_department_alter_student_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for ESP32 device', max_length=50, unique=True)),
                ('device_name', models.CharField(help_text="Human-readable name (e.g., 'CS101_Classroom_ESP32')", max_length=100)),
                ('ssid', models.CharField(help_text='WiFi network name created by ESP32', max_length=32)),
                ('password', models.CharField(help_text='WiFi password (if required)', max_length=64)),
                ('location', models.CharField(help_text="Physical location (e.g., 'Computer Science Lab 1')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time device was online')),
            ],
            options={
                'verbose_name': 'ESP32 Device',
                'verbose_name_plural': 'ESP32 Devices',
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='device_mac',
            field=models.CharField(blank=True, help_text='Student device MAC address', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='network_verified',
            field=models.BooleanField(default=False, help_text='Whether student was connected to ESP32 network'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='esp32_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_ui.esp32device'),
        ),
        migrations.CreateModel(
            name='NetworkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this network session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.course')),
                ('esp32_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.esp32device')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Session',
                'verbose_name_plural': 'Network Sessions',
            },
        ),
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Device MAC address', max_length=17)),
                ('device_name', models.CharField(blank=True, help_text='Device name if available', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('network_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_ui.networksession')),
            ],
            options={
                'verbose_name': 'Connected Device',
                'verbose_name_plural': 'Connected Devices',
                'unique_together': {('network_session', 'mac_address')},
            },
        ),
    ]
