# Generated by Django 5.2.3 on 2025-08-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0003_esp32device_attendancerecord_device_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networksession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
