# Generated by Django 5.2.5 on 2025-08-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0004_attendancerecord_marked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='time',
            field=models.TimeField(default='09:00:00', help_text='Time for this attendance session'),
        ),
    ]
