# Generated by Django 5.2.3 on 2025-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0004_alter_networksession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32device',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat received from ESP32', null=True),
        ),
    ]
